In [1]:
import pandas as pd
import numpy as np

In [2]:
ovr=pd.read_csv(r'C:\Users\User\Downloads\Final Override w_o Inn_Dis 0924.txt', sep='\t')

In [4]:
ovr.head()

,10.9 SO-FU-All PA,10.9 SO-FU-All PA: SLS_ORGN_ID,10.9 SO-FU-All PA: FU,10.9 SO-FU-All PA: All PA,8.4 SS Calendar Week: CY + FY Forecast,Innovation,Discontinuation,Final Override,Past 13 weeks Actuals,ML BL Rounded,Category Override,FG Override,FU Override,Final Evergreen Rounded
0,0001-10079400251906-000621-001133-Norcal Region,1,10079400251906,000621-001133,202139,False,False,False,0.0,2,0,0.0,0.0,2
1,0001-10079400251906-000621-001133-Norcal Region,1,10079400251906,000621-001133,202140,False,False,False,0.0,2,0,0.0,0.0,2
2,0001-10079400251906-000621-001133-Norcal Region,1,10079400251906,000621-001133,202141,False,False,False,0.0,2,0,0.0,0.0,2
3,0001-10079400251906-000621-001133-Norcal Region,1,10079400251906,000621-001133,202142,False,False,False,0.0,2,0,0.0,0.0,2
4,0001-10079400251906-000621-001133-Norcal Region,1,10079400251906,000621-001133,202143,False,False,False,0.0,2,0,0.0,0.0,2

In [53]:
ovr = ovr[(ovr['8.4 SS Calendar Week: CY + FY Forecast']==202140)&(ovr['10.9 SO-FU-All PA: All PA']=='003338-000000')]

In [46]:
ovr['10.9 SO-FU-All PA: All PA'].nunique()

367

In [47]:
ovr[(ovr['10.9 SO-FU-All PA: All PA']=='003338-000000')]

,10.9 SO-FU-All PA,10.9 SO-FU-All PA: SLS_ORGN_ID,Code,10.9 SO-FU-All PA: All PA,8.4 SS Calendar Week: CY + FY Forecast,Innovation,Discontinuation,Final Override,Past 13 weeks Actuals,ML BL Rounded,Category Override,FG Override,FU Override,Final Evergreen Rounded,Category,CS_UPC_NR_CD
353235,0001-10055086002391-003338-000000-Amazon,1,10055086002391,003338-000000,202139,False,False,False,448.0,31,0,0.0,0.0,31,DEO-MALE TOILETRIES,005508600239
353236,0001-10055086002391-003338-000000-Amazon,1,10055086002391,003338-000000,202140,False,False,False,448.0,34,0,0.0,0.0,34,DEO-MALE TOILETRIES,005508600239
353237,0001-10055086002391-003338-000000-Amazon,1,10055086002391,003338-000000,202141,False,False,False,448.0,33,0,0.0,0.0,33,DEO-MALE TOILETRIES,005508600239
353238,0001-10055086002391-003338-000000-Amazon,1,10055086002391,003338-000000,202142,False,False,False,448.0,31,0,0.0,0.0,31,DEO-MALE TOILETRIES,005508600239
353239,0001-10055086002391-003338-000000-Amazon,1,10055086002391,003338-000000,202143,False,False,False,448.0,48,0,0.0,0.0,48,DEO-MALE TOILETRIES,005508600239
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5942932,0001-10764302021824-003338-000000-Amazon,1,10764302021824,003338-000000,202248,True,False,True,0.0,0,0,0.0,200.0,200,SUNDIAL,076430202182
5942933,0001-10764302021824-003338-000000-Amazon,1,10764302021824,003338-000000,202249,True,False,True,0.0,0,0,0.0,200.0,200,SUNDIAL,076430202182
5942934,0001-10764302021824-003338-000000-Amazon,1,10764302021824,003338-000000,202250,True,False,True,0.0,0,0,0.0,200.0,200,SUNDIAL,076430202182
5942935,0001-10764302021824-003338-000000-Amazon,1,10764302021824,003338-000000,202251,True,False,True,0.0,0,0,0.0,200.0,200,SUNDIAL,076430202182
5942936,0001-10764302021824-003338-000000-Amazon,1,10764302021824,003338-000000,202252,True,False,True,0.0,0,0,0.0,200.0,200,SUNDIAL,076430202182

In [17]:
ovr.rename(columns={'10.9 SO-FU-All PA: FU': 'Code'}, inplace=True)

In [11]:
ac=pd.read_excel(r'C:\Users\User\Downloads\amazon accuracy (1).xlsx', sheet_name = 'W202140', header=1)

In [12]:
ac

,CS_UPC_NR_CD,Lock Phys Cs (21 10 14 report),SUPPLEMENTAL_VOLUME_NR (21 10 14 report),Phys Cs (21 10 14 report),Plans 21 09 23,Plans 21 07 26,TF 21 09 30,TF 21 07 30,Total ML forecast = CD forecst,ERROR_CD_21 10 14,...,ERROR_CD_21 07 26,ERROR_TF 21 09 30,ERROR_TF 21 07 30,check 1,check 2,check 3,check 4,check 5,check 6,check 7
0,2240000028,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0
1,2240000032,23,19.612152,0,23,0,19.612152,0.0,4,23,...,0,19.612152,0.0,1,1,0,1,0,1,0
2,2240000043,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0
3,2240000044,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0
4,2240000046,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1616,176430000000,0,0.000000,0,11,0,0.000000,0.0,1,0,...,0,0.000000,0.0,0,0,0,1,0,0,0
1617,871160000000,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0
1618,871160000000,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0
1619,871170000000,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0
1620,871256000000,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0

In [13]:
ac = ac[ac['Total ML forecast = CD forecst']==7]

,CS_UPC_NR_CD,Lock Phys Cs (21 10 14 report),SUPPLEMENTAL_VOLUME_NR (21 10 14 report),Phys Cs (21 10 14 report),Plans 21 09 23,Plans 21 07 26,TF 21 09 30,TF 21 07 30,Total ML forecast = CD forecst,ERROR_CD_21 10 14,...,ERROR_CD_21 07 26,ERROR_TF 21 09 30,ERROR_TF 21 07 30,check 1,check 2,check 3,check 4,check 5,check 6,check 7
41,2240000270,38,38.464714,28,38,29,38.0,35.129009,7,10,...,1,10.0,7.129009,1,1,1,1,1,1,1
47,2240000327,69,61.560623,7,69,60,62.0,63.682823,7,62,...,53,55.0,56.682823,1,1,1,1,1,1,1
50,2240000330,53,47.793533,38,53,48,48.0,48.883482,7,15,...,10,10.0,10.883482,1,1,1,1,1,1,1
63,2240000532,139,144.391220,22,139,61,144.0,54.539589,7,117,...,39,122.0,32.539589,1,1,1,1,1,1,1
68,2240000554,17,16.753837,13,17,21,17.0,10.843996,7,4,...,8,4.0,2.156004,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1562,76430229001,28,15.910981,24,28,7,16.0,7.726742,7,4,...,17,8.0,16.273258,1,1,1,1,1,1,1
1579,76430229061,114,109.510178,262,114,202,110.0,158.269300,7,148,...,60,152.0,103.730700,1,1,1,1,1,1,1
1592,76430290138,5,3.576277,93,5,3,4.0,5.916310,7,88,...,90,89.0,87.083690,1,1,1,1,1,1,1
1606,76430290502,59,98.371345,148,59,165,98.0,43.702208,7,89,...,17,50.0,104.297792,1,1,1,1,1,1,1
1607,76430290503,56,79.038938,21,56,20,79.0,49.117528,7,35,...,1,58.0,28.117528,1,1,1,1,1,1,1

In [23]:
ac['CS_UPC_NR_CD'] = ac['CS_UPC_NR_CD'].astype(str).str.zfill(12)

In [14]:
ph=pd.read_excel(r'C:\Users\User\Downloads\DHUB PH Extract (6).xlsx', usecols=['Code', 'Find CaseUPC', 'Category'])

C:\Users\User\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:221: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [15]:
ph

                 Code             Category  Find CaseUPC
0      10079400277760  DEO-MALE TOILETRIES  007940027776
1      10079400048636  DEO-MALE TOILETRIES  007940004863
2      10079400473537  DEO-MALE TOILETRIES  007940047353
3      10079400106381  DEO-MALE TOILETRIES  007940010638
4      10079400312973  DEO-MALE TOILETRIES  007940031297
...               ...                  ...           ...
40246  10055451002148           ELIDA HAIR  005545100214
40247  10055451002124           ELIDA HAIR  005545100212
40248  10055451002117           ELIDA HAIR  005545100211
40249  10055451002131           ELIDA HAIR  005545100213
40250  80055451526230           ELIDA HAIR  005545152623

[40251 rows x 3 columns]

In [16]:
ph.rename(columns={'Find CaseUPC': 'CS_UPC_NR_CD'}, inplace=True)

In [18]:
ovr.head()

,10.9 SO-FU-All PA,10.9 SO-FU-All PA: SLS_ORGN_ID,Code,10.9 SO-FU-All PA: All PA,8.4 SS Calendar Week: CY + FY Forecast,Innovation,Discontinuation,Final Override,Past 13 weeks Actuals,ML BL Rounded,Category Override,FG Override,FU Override,Final Evergreen Rounded
0,0001-10079400251906-000621-001133-Norcal Region,1,10079400251906,000621-001133,202139,False,False,False,0.0,2,0,0.0,0.0,2
1,0001-10079400251906-000621-001133-Norcal Region,1,10079400251906,000621-001133,202140,False,False,False,0.0,2,0,0.0,0.0,2
2,0001-10079400251906-000621-001133-Norcal Region,1,10079400251906,000621-001133,202141,False,False,False,0.0,2,0,0.0,0.0,2
3,0001-10079400251906-000621-001133-Norcal Region,1,10079400251906,000621-001133,202142,False,False,False,0.0,2,0,0.0,0.0,2
4,0001-10079400251906-000621-001133-Norcal Region,1,10079400251906,000621-001133,202143,False,False,False,0.0,2,0,0.0,0.0,2

In [19]:
ovr = pd.merge(ovr, ph, how='left')

In [20]:
ovr.head()

,10.9 SO-FU-All PA,10.9 SO-FU-All PA: SLS_ORGN_ID,Code,10.9 SO-FU-All PA: All PA,8.4 SS Calendar Week: CY + FY Forecast,Innovation,Discontinuation,Final Override,Past 13 weeks Actuals,ML BL Rounded,Category Override,FG Override,FU Override,Final Evergreen Rounded,Category,CS_UPC_NR_CD
0,0001-10079400251906-000621-001133-Norcal Region,1,10079400251906,000621-001133,202139,False,False,False,0.0,2,0,0.0,0.0,2,DEO-MALE TOILETRIES,007940025190
1,0001-10079400251906-000621-001133-Norcal Region,1,10079400251906,000621-001133,202140,False,False,False,0.0,2,0,0.0,0.0,2,DEO-MALE TOILETRIES,007940025190
2,0001-10079400251906-000621-001133-Norcal Region,1,10079400251906,000621-001133,202141,False,False,False,0.0,2,0,0.0,0.0,2,DEO-MALE TOILETRIES,007940025190
3,0001-10079400251906-000621-001133-Norcal Region,1,10079400251906,000621-001133,202142,False,False,False,0.0,2,0,0.0,0.0,2,DEO-MALE TOILETRIES,007940025190
4,0001-10079400251906-000621-001133-Norcal Region,1,10079400251906,000621-001133,202143,False,False,False,0.0,2,0,0.0,0.0,2,DEO-MALE TOILETRIES,007940025190

In [38]:
ac

,CS_UPC_NR_CD,Lock Phys Cs (21 10 14 report),SUPPLEMENTAL_VOLUME_NR (21 10 14 report),Phys Cs (21 10 14 report),Plans 21 09 23,Plans 21 07 26,TF 21 09 30,TF 21 07 30,Total ML forecast = CD forecst,ERROR_CD_21 10 14,...,ERROR_CD_21 07 26,ERROR_TF 21 09 30,ERROR_TF 21 07 30,check 1,check 2,check 3,check 4,check 5,check 6,check 7
0,002240000028,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0
1,002240000032,23,19.612152,0,23,0,19.612152,0.0,4,23,...,0,19.612152,0.0,1,1,0,1,0,1,0
2,002240000043,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0
3,002240000044,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0
4,002240000046,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1616,176430000000,0,0.000000,0,11,0,0.000000,0.0,1,0,...,0,0.000000,0.0,0,0,0,1,0,0,0
1617,871160000000,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0
1618,871160000000,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0
1619,871170000000,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0
1620,871256000000,0,0.000000,0,0,0,0.000000,0.0,0,0,...,0,0.000000,0.0,0,0,0,0,0,0,0

In [54]:
df = pd.merge(ac, ovr, how='left', on='CS_UPC_NR_CD')

In [55]:
df

,CS_UPC_NR_CD,Lock Phys Cs (21 10 14 report),SUPPLEMENTAL_VOLUME_NR (21 10 14 report),Phys Cs (21 10 14 report),Plans 21 09 23,Plans 21 07 26,TF 21 09 30,TF 21 07 30,Total ML forecast = CD forecst,ERROR_CD_21 10 14,...,Innovation,Discontinuation,Final Override,Past 13 weeks Actuals,ML BL Rounded,Category Override,FG Override,FU Override,Final Evergreen Rounded,Category
0,002240000028,0,0.000000,0,0,0,0.000000,0.0,0,0,...,False,True,False,0.0,0.0,0.0,0.0,0.0,0.0,HAIR CARE
1,002240000032,23,19.612152,0,23,0,19.612152,0.0,4,23,...,False,False,True,409.0,0.0,0.0,0.0,23.0,23.0,HAIR CARE
2,002240000043,0,0.000000,0,0,0,0.000000,0.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,002240000044,0,0.000000,0,0,0,0.000000,0.0,0,0,...,False,True,False,0.0,0.0,0.0,0.0,0.0,0.0,HAIR CARE
4,002240000046,0,0.000000,0,0,0,0.000000,0.0,0,0,...,False,True,False,0.0,0.0,0.0,0.0,0.0,0.0,HAIR CARE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1616,176430000000,0,0.000000,0,11,0,0.000000,0.0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1617,871160000000,0,0.000000,0,0,0,0.000000,0.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1618,871160000000,0,0.000000,0,0,0,0.000000,0.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1619,871170000000,0,0.000000,0,0,0,0.000000,0.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1620,871256000000,0,0.000000,0,0,0,0.000000,0.0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
df['FU Override'].sum()

33927.5901

In [58]:
df['SUPPLEMENTAL_VOLUME_NR (21 10 14 report)'].sum()

73144.093592

In [59]:
df['Lock Phys Cs (21 10 14 report)'].sum()

84574

In [ ]:
df['Lock Phys Cs (21 10 14 report)'].sum()

In [ ]:
df['Lock Phys Cs (21 10 14 report)'].sum()

In [ ]:
df['FU Override'].sum()

In [62]:
df.describe()

,Lock Phys Cs (21 10 14 report),SUPPLEMENTAL_VOLUME_NR (21 10 14 report),Phys Cs (21 10 14 report),Plans 21 09 23,Plans 21 07 26,TF 21 09 30,TF 21 07 30,Total ML forecast = CD forecst,ERROR_CD_21 10 14,ERROR_ML_21 10 14,...,check 7,10.9 SO-FU-All PA: SLS_ORGN_ID,Code,8.4 SS Calendar Week: CY + FY Forecast,Past 13 weeks Actuals,ML BL Rounded,Category Override,FG Override,FU Override,Final Evergreen Rounded
count,1621.000000,1621.000000,1621.00000,1621.000000,1621.000000,1621.000000,1621.000000,1621.000000,1621.000000,1621.000000,...,1621.000000,1142.0,1.142000e+03,1142.0,1142.000000,1142.000000,1142.0,1142.0,1142.000000,1142.000000
mean,52.173967,45.122821,48.05182,68.785318,50.243677,51.090808,44.371090,1.779766,56.535472,55.323919,...,0.282542,1.0,1.056464e+13,202140.0,1188.145359,71.652364,0.0,0.0,29.708923,94.789842
std,335.885225,276.339369,623.19918,378.684517,278.350067,281.512636,267.594550,2.698008,407.018469,495.058171,...,0.450374,0.0,4.640042e+12,0.0,5318.294257,350.554259,0.0,0.0,277.208057,437.132728
min,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.0,2.240064e+10,202140.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
25%,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.0,1.007940e+13,202140.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
50%,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.0,1.007940e+13,202140.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
75%,2.000000,1.780334,0.00000,9.000000,4.000000,7.601822,3.568452,4.000000,3.000000,3.444667,...,1.000000,1.0,1.076430e+13,202140.0,480.000000,26.750000,0.0,0.0,0.000000,37.000000
max,9778.000000,9508.076172,17346.00000,9778.000000,5000.000000,9508.000000,7425.983720,7.000000,12346.000000,17346.000000,...,1.000000,1.0,7.007940e+13,202140.0,126334.000000,9778.000000,0.0,0.0,5000.000000,9778.000000

In [63]:
df.sum()

CS_UPC_NR_CD                                0022400000280022400000320022400000430022400000...
Lock Phys Cs (21 10 14 report)                                                          84574
SUPPLEMENTAL_VOLUME_NR (21 10 14 report)                                         73144.093592
Phys Cs (21 10 14 report)                                                               77892
Plans 21 09 23                                                                         111501
Plans 21 07 26                                                                          81445
TF 21 09 30                                                                      82818.200154
TF 21 07 30                                                                      71925.536225
Total ML forecast = CD forecst                                                           2885
ERROR_CD_21 10 14                                                                       91644
ERROR_ML_21 10 14                                                                89680.073116
ERROR_CD_21 09 23                                                                      118571
ERROR_CD_21 07 26                                                                      108403
ERROR_TF 21 09 30                                                                99350.402984
ERROR_TF 21 07 30                                                                99528.523743
check 1                                                                                   409
check 2                                                                                   417
check 3                                                                                   219
check 4                                                                                   476
check 5                                                                                   442
check 6                                                                                   464
check 7                                                                                   458
10.9 SO-FU-All PA: SLS_ORGN_ID                                                         1142.0
Code                                                                      12064820306423336.0
8.4 SS Calendar Week: CY + FY Forecast                                            230843880.0
Innovation                                                                                 20
Discontinuation                                                                           636
Final Override                                                                             66
Past 13 weeks Actuals                                                               1356862.0
ML BL Rounded                                                                         81827.0
Category Override                                                                         0.0
FG Override                                                                               0.0
FU Override                                                                        33927.5901
Final Evergreen Rounded                                                              108250.0
dtype: object

In [106]:
df7 = df[df['Total ML forecast = CD forecst']==7]

In [107]:
df7.sum()

CS_UPC_NR_CD                                0022400002700022400003270022400003300022400005...
Lock Phys Cs (21 10 14 report)                                                          48595
SUPPLEMENTAL_VOLUME_NR (21 10 14 report)                                         43950.717914
Phys Cs (21 10 14 report)                                                               54521
Plans 21 09 23                                                                          48595
Plans 21 07 26                                                                          27693
TF 21 09 30                                                                           43952.0
TF 21 07 30                                                                      34956.029068
Total ML forecast = CD forecst                                                           1176
ERROR_CD_21 10 14                                                                       44726
ERROR_ML_21 10 14                                                                 38343.14758
ERROR_CD_21 09 23                                                                       44726
ERROR_CD_21 07 26                                                                       43490
ERROR_TF 21 09 30                                                                     38339.0
ERROR_TF 21 07 30                                                                 40411.50008
check 1                                                                                   168
check 2                                                                                   168
check 3                                                                                   168
check 4                                                                                   168
check 5                                                                                   168
check 6                                                                                   168
check 7                                                                                   168
10.9 SO-FU-All PA                           0001-10022400002702-003338-000000-Amazon0001-1...
10.9 SO-FU-All PA: SLS_ORGN_ID                                                          168.0
Code                                                                       1697081696744383.0
10.9 SO-FU-All PA: All PA                   003338-000000003338-000000003338-000000003338-...
8.4 SS Calendar Week: CY + FY Forecast                                             33959520.0
Innovation                                                                                  0
Discontinuation                                                                             2
Final Override                                                                              3
Past 13 weeks Actuals                                                                620386.0
ML BL Rounded                                                                         44588.0
Category Override                                                                         0.0
FG Override                                                                               0.0
FU Override                                                                            578.01
Final Evergreen Rounded                                                               45022.0
Category                                    HAIR CAREDEO-MALE TOILETRIESDEO-MALE TOILETRIE...
dtype: object

In [109]:
df['CS_UPC_NR_CD'].nunique()

1620

In [108]:
df7['CS_UPC_NR_CD'].nunique()

168

In [99]:
bb = pd.read_excel(r'C:\Users\User\OneDrive - ООО «Эдвансд»\requests\amazon bb 2020-03-01.xlsx')

In [100]:
bb

,Planned Account,UPC,CS_UPC,Ordinal Week,Plan Phys Cs,Plan Phys Cs Promo,Plan Phys Cs NP,Plan Base Phys Cs,Unnamed: 8
0,003338 - AmazonDotCom,001111100131-Dove BW CM Shower Foam 1(2) 13.5z,001111100131,"Week Ending Sep 05, 2021",184.0,0.0,184.0,164.0,NaN
1,003338 - AmazonDotCom,001111100131-Dove BW CM Shower Foam 1(2) 13.5z,001111100131,"Week Ending Sep 12, 2021",178.0,0.0,178.0,159.0,NaN
2,003338 - AmazonDotCom,001111100131-Dove BW CM Shower Foam 1(2) 13.5z,001111100131,"Week Ending Sep 19, 2021",173.0,0.0,173.0,154.0,NaN
3,003338 - AmazonDotCom,001111100131-Dove BW CM Shower Foam 1(2) 13.5z,001111100131,"Week Ending Sep 26, 2021",173.0,0.0,173.0,154.0,NaN
4,003338 - AmazonDotCom,001111100131-Dove BW CM Shower Foam 1(2) 13.5z,001111100131,"Week Ending Oct 03, 2021",173.0,0.0,173.0,154.0,NaN
...,...,...,...,...,...,...,...,...,...
93945,003338 - AmazonDotCom,871256686550-LPT PG TIPS PYR BLACK 6 40CT,871256686550,"Week Ending Jan 30, 2022",0.0,0.0,0.0,0.0,NaN
93946,003338 - AmazonDotCom,871256686550-LPT PG TIPS PYR BLACK 6 40CT,871256686550,"Week Ending Feb 06, 2022",0.0,0.0,0.0,0.0,NaN
93947,003338 - AmazonDotCom,871256686550-LPT PG TIPS PYR BLACK 6 40CT,871256686550,"Week Ending Feb 13, 2022",0.0,0.0,0.0,0.0,NaN
93948,003338 - AmazonDotCom,871256686550-LPT PG TIPS PYR BLACK 6 40CT,871256686550,"Week Ending Feb 20, 2022",0.0,0.0,0.0,0.0,NaN
93949,003338 - AmazonDotCom,871256686550-LPT PG TIPS PYR BLACK 6 40CT,871256686550,"Week Ending Feb 27, 2022",0.0,0.0,0.0,0.0,NaN

In [101]:
bb.rename(columns={'CS_UPC':'CS_UPC_NR_CD', 'Plan Phys Cs':'Total FC', 'Plan Phys Cs Promo':'Promo', 'Plan Phys Cs NP':'BL + BB', 'Plan Base Phys Cs':'BL'}, inplace = True)

In [102]:
bb['CS_UPC_NR_CD']=bb['CS_UPC_NR_CD'].astype(str).str.zfill(12)

In [103]:
bb = bb[bb['Ordinal Week']=='Week Ending Oct 10, 2021']

In [110]:
df7 = df7.merge(bb, how='left')

In [111]:
df7['CS_UPC_NR_CD'].nunique()

168

In [112]:
df7.sum()

CS_UPC_NR_CD                                0022400002700022400003270022400003300022400005...
Lock Phys Cs (21 10 14 report)                                                          48595
SUPPLEMENTAL_VOLUME_NR (21 10 14 report)                                         43950.717914
Phys Cs (21 10 14 report)                                                               54521
Plans 21 09 23                                                                          48595
Plans 21 07 26                                                                          27693
TF 21 09 30                                                                           43952.0
TF 21 07 30                                                                      34956.029068
Total ML forecast = CD forecst                                                           1176
ERROR_CD_21 10 14                                                                       44726
ERROR_ML_21 10 14                                                                 38343.14758
ERROR_CD_21 09 23                                                                       44726
ERROR_CD_21 07 26                                                                       43490
ERROR_TF 21 09 30                                                                     38339.0
ERROR_TF 21 07 30                                                                 40411.50008
check 1                                                                                   168
check 2                                                                                   168
check 3                                                                                   168
check 4                                                                                   168
check 5                                                                                   168
check 6                                                                                   168
check 7                                                                                   168
10.9 SO-FU-All PA                           0001-10022400002702-003338-000000-Amazon0001-1...
10.9 SO-FU-All PA: SLS_ORGN_ID                                                          168.0
Code                                                                       1697081696744383.0
10.9 SO-FU-All PA: All PA                   003338-000000003338-000000003338-000000003338-...
8.4 SS Calendar Week: CY + FY Forecast                                             33959520.0
Innovation                                                                                  0
Discontinuation                                                                             2
Final Override                                                                              3
Past 13 weeks Actuals                                                                620386.0
ML BL Rounded                                                                         44588.0
Category Override                                                                         0.0
FG Override                                                                               0.0
FU Override                                                                            578.01
Final Evergreen Rounded                                                               45022.0
Category                                    HAIR CAREDEO-MALE TOILETRIESDEO-MALE TOILETRIE...
Planned Account                             003338 - AmazonDotCom003338 - AmazonDotCom0033...
UPC                                         002240000270-TRES SA Root Touch Up DK Brown 6p...
Ordinal Week                                Week Ending Oct 10, 2021Week Ending Oct 10, 20...
Total FC                                                                              48268.0
Promo                                                                                     0.0
BL + BB                                                                               48268.0
BL                                                                                    45342.0
Unnamed: 8                                                                                0.0
dtype: object

In [118]:
df7[df7['Total FC']!=df7['Lock Phys Cs (21 10 14 report)']]['CS_UPC_NR_CD'].nunique()

2

In [117]:
df7[df7['Total FC']==df7['Lock Phys Cs (21 10 14 report)']]['CS_UPC_NR_CD'].nunique()

166

In [123]:
df7['Total FC difference'] = df7['Lock Phys Cs (21 10 14 report)']-df7['Total FC']

In [124]:
df7['Total FC difference'].sum()

327.0

In [125]:
df7[df7['BL']!=df7['SUPPLEMENTAL_VOLUME_NR (21 10 14 report)']]['CS_UPC_NR_CD'].nunique()

168

In [126]:
df7[df7['BL']==df7['SUPPLEMENTAL_VOLUME_NR (21 10 14 report)']]['CS_UPC_NR_CD'].nunique()

0

In [127]:
df7['BL difference'] = df7['SUPPLEMENTAL_VOLUME_NR (21 10 14 report)']-df7['BL']

In [128]:
df7['BL difference'].sum()

-1391.2820860000006

In [129]:
df7

,CS_UPC_NR_CD,Lock Phys Cs (21 10 14 report),SUPPLEMENTAL_VOLUME_NR (21 10 14 report),Phys Cs (21 10 14 report),Plans 21 09 23,Plans 21 07 26,TF 21 09 30,TF 21 07 30,Total ML forecast = CD forecst,ERROR_CD_21 10 14,...,Planned Account,UPC,Ordinal Week,Total FC,Promo,BL + BB,BL,Unnamed: 8,Total FC difference,BL difference
0,002240000270,38,38.464714,28,38,29,38.0,35.129009,7,10,...,003338 - AmazonDotCom,002240000270-TRES SA Root Touch Up DK Brown 6p...,"Week Ending Oct 10, 2021",38.0,0.0,38.0,38.0,NaN,0.0,0.464714
1,002240000327,69,61.560623,7,69,60,62.0,63.682823,7,62,...,003338 - AmazonDotCom,002240000327-SCH DS Bergamot + Lime GS1 12p 3.25z,"Week Ending Oct 10, 2021",69.0,0.0,69.0,69.0,NaN,0.0,-7.439377
2,002240000330,53,47.793533,38,53,48,48.0,48.883482,7,15,...,003338 - AmazonDotCom,002240000330-SCH DS Charcoal + Magnesium 12p 3...,"Week Ending Oct 10, 2021",53.0,0.0,53.0,53.0,NaN,0.0,-5.206467
3,002240000532,139,144.391220,22,139,61,144.0,54.539589,7,117,...,003338 - AmazonDotCom,002240000532-SCH DS Jasmine Tea SS 1(3) 3.25z,"Week Ending Oct 10, 2021",139.0,0.0,139.0,139.0,NaN,0.0,5.391220
4,002240000554,17,16.753837,13,17,21,17.0,10.843996,7,4,...,003338 - AmazonDotCom,002240000554-SCH DS Hemp RS+BLK PPR SS 12p 3.2...,"Week Ending Oct 10, 2021",17.0,0.0,17.0,17.0,NaN,0.0,-0.246163
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,076430229001,28,15.910981,24,28,7,16.0,7.726742,7,4,...,003338 - AmazonDotCom,076430229001-SM CH BDY LTN Brightening/Toning ...,"Week Ending Oct 10, 2021",28.0,0.0,28.0,28.0,NaN,0.0,-12.089019
164,076430229061,114,109.510178,262,114,202,110.0,158.269300,7,148,...,003338 - AmazonDotCom,076430229061-SM CH Frizz-Free Curl Mousse 12p ...,"Week Ending Oct 10, 2021",114.0,0.0,114.0,114.0,NaN,0.0,-4.489822
165,076430290138,5,3.576277,93,5,3,4.0,5.916310,7,88,...,003338 - AmazonDotCom,076430290138-SM RSCAO Baby Lotion Calm+Comfort...,"Week Ending Oct 10, 2021",5.0,0.0,5.0,5.0,NaN,0.0,-1.423723
166,076430290502,59,98.371345,148,59,165,98.0,43.702208,7,89,...,003338 - AmazonDotCom,076430290502-SM CH Kids DTGLR Ext Moisturizing...,"Week Ending Oct 10, 2021",59.0,0.0,59.0,59.0,NaN,0.0,39.371345
167,076430290503,56,79.038938,21,56,20,79.0,49.117528,7,35,...,003338 - AmazonDotCom,076430290503-SM CH Kids Curling Butter Cream 1...,"Week Ending Oct 10, 2021",56.0,0.0,56.0,56.0,NaN,0.0,23.038938